// This file will be generated by Supabase CLI
// For now, we'll use a basic structure
export interface Database {
  public: {
    Tables: {
      subscriptions: {
        Row: {
          id: string;
          user_id: string;
          service_name: string;
          amount: number;
          currency: string;
          billing_cycle: string;
          renewal_date: string;
          category: string;
          payment_method: string;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          service_name: string;
          amount: number;
          currency: string;
          billing_cycle: string;
          renewal_date: string;
          category: string;
          payment_method: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          service_name?: string;
          amount?: number;
          currency?: string;
          billing_cycle?: string;
          renewal_date?: string;
          category?: string;
          payment_method?: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
  };
}
